### ISSUE TITLE
GPX tracks don't delete.

### ISSUE THREAD

**Issue by BjornRasmussen** [openstreetmap/gpx-updater#7] opened 2018-08-12 14:24 UTC
My GPX tracks that I deleted from OSM last year have still not been removed from this layer.  It is quite annoying, because I have a large number of them leaving my house, easy for anyone on the internet to see.  Would it be possible to stop showing deleted traces?

**Comment by lukie80** [comment] 2018-08-13 11:46
If I assume correctly, deleting the traces from the traces layer is not possible without re-processing of **all** GPS traces in the database, which would probably take ages.
Nevertheless, the only information people can deduce from your anonymous traces is that "someone who lives in this house is recording GPS traces". So it draws attention but contains no personal information.

**Comment by Silva1989** [comment] 2022-03-20 13:05
Can anyone please address this issue? This is a serious problem, as in my case there are tracks inside (my own) private property. They are already deleted, so it's not acceptable that it stays not only online but accessible to anyone

**Comment by leifr-unc** [comment] 2022-03-24 17:56
I also still have gpx traces in my yard.  At one point, I uploaded a map of parcels as a gpx so I could use it for drawing park outlines, but have since deleted it.  The map in my area is so polluted with parcel gpx lines that the overlay is basically unusable.  
Someone needs to fix this.

**Comment by Firefishy** [comment] 2023-07-27 15:01
We re-rendered the full dataset earlier this year. The rebuilt took >2 week. An option might be to do this on a regular interval.

**Comment by Firefishy** [comment] 2023-07-27 15:02
Duplicate of https://github.com/openstreetmap/gpx-updater/issues/4

**Closed by Firefishy** 2023-07-27 15:02 UTC
